### ISSUE TITLE
D-Wave examples break during scheduled maintenance windows

### ISSUE THREAD

**Issue by jonbest-aws** [aws/amazon-braket-examples#117]
At least the max cut example [0] breaks during D-Wave maintenance windows due to the Advantage_system4 ARN being hardcoded. Should these use auto-selection? 

[0] https://github.com/aws/amazon-braket-examples/blob/main/examples/quantum_annealing/Dwave_MaximumCut.ipynb

**Comment by christianbmadsen** [comment]
Thank you for the call-out @jonbest-aws. 

For DWave we have two options to prevent the issue

**Option 1 - Instantiate sampler without specifying the device**
Use the first available DWave device for the sampler so long as the problem allows it (see https://github.com/aws/amazon-braket-ocean-plugin-python/blob/main/src/braket/ocean_plugin/braket_sampler.py#L61-L63).

**Option 2 - Use branching logic to find an online solver**
If the Advantage solver is needed branching logic like the following can be used instead
```
device_arns = AwsDevice.get_devices(provider_names=["D-Wave Systems"], statuses=["ONLINE"])
adv_device_arns = filter(lambda arn: "Advantage" in arn, device_arns)
sampler = BraketDWaveSampler(adv_device_arns[0])
```

For completeness, we are using the Advantage_system4 ARN explicitly in 7 files

1. Getting_Devices_and_Checking_Device_Properties.ipynb
2. Dwave_GraphPartitioning.ipynb
3. Dwave_MinimumVertexCoverProblem.ipynb
4. Dwave_MaximumCut.ipynb
5. Dwave_Anatomy.ipynb
6. Dwave_StructuralImbalance/Dwave_StructuralImbalance.ipynb
7. Running_large_problems_using_QBSolv.ipynb

As a final note it looks like cell 3 in https://github.com/aws/amazon-braket-examples/blob/main/examples/quantum_annealing/Dwave_MaximumCut.ipynb could just be removed.

**Comment by JuanGiraldo0212** [comment]
Hi, I'm working on this issue.

**Comment by christianbmadsen** [comment]
Great! Thank you @JuanGiraldo0212. If you have questions as you go along just post them to this issue and we will provide answers.

**Comment by JuanGiraldo0212** [comment]
Thanks @christianbmadsen, quick question, some other files have the same cell that you mentioned should be deleted on https://github.com/aws/amazon-braket-examples/blob/main/examples/quantum_annealing/Dwave_MaximumCut.ipynb, should I also delete it in:
- https://github.com/aws/amazon-braket-examples/blob/main/examples/quantum_annealing/Dwave_GraphPartitioning.ipynb
-  https://github.com/aws/amazon-braket-examples/blob/main/examples/quantum_annealing/Dwave_MinimumVertexCoverProblem.ipynb
-  https://github.com/aws/amazon-braket-examples/blob/main/examples/quantum_annealing/Dwave_StructuralImbalance/Dwave_StructuralImbalance.ipynb
Thanks.

**Comment by christianbmadsen** [comment]
@JuanGiraldo0212 that would be great! Thanks!

**Comment by JuanGiraldo0212** [comment]
Thanks @christianbmadsen, do I need some permissions to push the branch and create the PR?

**Comment by christianbmadsen** [comment]
@JuanGiraldo0212 have you forked the repo? You want to fork the repo, do your development and then create the PR from your fork.

**Comment by JuanGiraldo0212** [comment]
Sorry I forgot to fork it, my bad. I just created the PR @christianbmadsen

**Comment by christianbmadsen** [comment]
Thank you for the PR. We will take a look and provide feedback!

**Comment by JuanGiraldo0212** [comment]
Thanks

**Comment by christianbmadsen** [comment]
DWave examples were removed in November. Closing this issue.
