### ISSUE TITLE
Error in Braket examples/ quantum_annealing/ Dwave_TSP_Braket

### ISSUE THREAD

**Issue by w601sxs** [aws/amazon-braket-examples#12]
`ModuleNotFoundError: No module named 'pandas'`

either add line to install or check conda_braket environment

**Comment by w601sxs** [comment]
Fix `import pandas as pda` to "pd" otherwise following cells will break

**Comment by w601sxs** [comment]
Also will be useful to see a comparison of where QUBO does faster than simulated annealing at the end of the notebook. Given that even without grid search, SA found the right min distance?

**Comment by floralph** [comment]
Pandas was added to the conda_braket environment for a revision released during re:Invent.  Newly launched notebook instances as well as stopped/started instances will have the latest revision including pandas.
