### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by learnercrypto** [aws/amazon-braket-examples#165]
**Describe the bug**
All of these links are broken:
https://github.com/aws/amazon-braket-examples/blob/main/examples/pennylane/0_Getting_started.ipynb
https://github.com/aws/amazon-braket-examples/blob/main/examples/pennylane/1_Parallelized_optimization_of_quantum_circuits.ipynb
https://github.com/aws/amazon-braket-examples/blob/main/examples/pennylane/2_Graph_optimization_with_QAOA.ipynb
https://github.com/aws/amazon-braket-examples/blob/main/examples/pennylane/3_Quantum_chemistry_with_VQE.ipynb

**To Reproduce**
1. Go to **_Quantum machine learning and optimization with PennyLane_**
2. Click on Links

**Comment by christianbmadsen** [comment]
@learnercrypto Thank you for pointing out the broken links! Let us know if you'd like to raise a PR to fix them (the correct links can be found by navigating this repo). If you are not planning to submit a PR we will do it on our end.

**Comment by learnercrypto** [comment]
@christianbmadsen, may I ask you please to submit PR? if it doesn't make too much trouble
