### ISSUE TITLE
Can't find controlled-RY gate in Amazon Braket SDK.

### ISSUE THREAD

**Issue by AWIS99** [aws/amazon-braket-examples#189]
I am searching for qiskit.circuit.QuantumCircuit.cry( ) methods equivalent function in Amazon Braket SDK. I also tried writing the code in Qiskit first and then run it using the Qiskit provider for Amazon Braket. But it also throws key error for cry( ) function. Please help.

![image](https://user-images.githubusercontent.com/52231621/193253329-1cb4ed71-b8da-4e85-b253-bb523db0ea89.png)

**Comment by ajberdy** [comment]
Hi, we currently do not have a `cry` gate. Depending on your use case, you may pass a custom `unitary` gate with the corresponding matrix. Additionally, you may be interested in using OpenQASM to submit your programs to the LocalSimulator, which currently supports arbitrary control modifiers on gates. For example `ctrl @ ry(theta) c, q;` would give a controlled RY gate on q, controlled by c. You can find more info about simulating OpenQASM programs on the local simulator in our [example notebook](https://github.com/aws/amazon-braket-examples/blob/main/examples/braket_features/Simulating_Advanced_OpenQASM_Programs_with_the_Local_Simulator.ipynb). Please let me know if you have any more questions!
