### ISSUE TITLE
The link to AllSinglesDoubles is broken

### ISSUE THREAD

**Issue by sita158** [aws/amazon-braket-examples#237]
**Describe the bug**
The link to the AllSinglesDoubles Pennylane documentation in the "Defining an ansatz circuit" section of the amazon-braket-examples/examples/pennylane/3_Hydrogen_Molecule_geometry_with_VQE/ notebook is broken. It should point to: https://docs.pennylane.ai/en/stable/code/api/pennylane.AllSinglesDoubles.html

**To Reproduce**
1. Go to amazon-braket-examples/examples/pennylane/3_Hydrogen_Molecule_geometry_with_VQE/
2. Scroll down to 'Defining an ansatz circuit section'
3. Click 'AllSinglesDoubles' link
5. See error

**Expected behavior**
Open Pennylane documentation on the AllSinglesDoubles ansatz: https://docs.pennylane.ai/en/stable/code/api/pennylane.AllSinglesDoubles.html

**Comment by ajberdy** [comment]
Thank you for raising this issue! I've created a PR to fix the link and will have it merged shortly
