### ISSUE TITLE
Typo: Conflicting number of shots in example notebook

### ISSUE THREAD

**Issue by vprusso** [aws/amazon-braket-examples#290]
This is minor, but in the following example [Jupyter notebook](https://github.com/aws/amazon-braket-examples/blob/main/examples/braket_features/Error_Mitigation_on_Amazon_Braket.ipynb):

Under the "Aria" section, the first sentence states:

> First, run we the QPE circuit on the Aria device with the maximum number of shots per task (5,000).

with a subsequent line of:

```py
task = device.run(circ, shots=2500)
print(task)
```

A few things:

- "we" and "run" should be switched
- Perhaps this is implied, but from the reading of this sentence it seems to indicate that you are running for the maximum number of shots (5,000), but then subsequently run it for the minimum number of shots required for debiasing (2,500).

**Comment by christianbmadsen** [comment]
@vprusso thanks so much for raising these content issues! I have created https://github.com/aws/amazon-braket-examples/pull/291 to fix them.
