### ISSUE TITLE
Getting_notifications_when_a_task_completes.ipynb does not render successfully

### ISSUE THREAD

**Issue by JDWhitfieldAWS** [aws/amazon-braket-examples#298]
**Describe the bug**
The "Getting_notifications_when_a_task_completes.ipynb" in folder "/examples/braket_features/Getting_notifications_when_a_task_completes" does not load the the github preview 

**To Reproduce**
1. Go to https://github.com/aws/amazon-braket-examples/tree/main/examples/braket_features/Getting_notifications_when_a_task_completes
2. Click on 'Getting_notifications_when_a_task_completes.ipynb'
3. See error "An error occurred"

**Expected behavior**
The notebook preview should display

**Screenshots**
<img width="1440" alt="error-msg 'An error occurred'" src="https://github.com/aws/amazon-braket-examples/assets/117700670/373afe9b-42b4-45cc-a2d2-b06e4fb4d4f0">

**Comment by guomanmin** [comment]
Getting_notifications_when_a_task_completes.ipynb's last commit was one year ago. I tried viewing commit (the source version) on GitHub, and it is running into the same issue. 

Validated that the Getting_notifications_when_a_task_completes.ipynb render noramlly locally and in console. This looks to be a Github hosting issue.
![image](https://github.com/aws/amazon-braket-examples/assets/23483181/123d84d1-7bd7-4847-8aa6-9dcf3733c6a4)


This is likely related to #3555

**Comment by JDWhitfieldAWS** [comment]
Looks like it is the same issue as https://github.com/jupyter/notebook/issues/3555 (which also has no resolution) so I'm closing this now
