### ISSUE TITLE
incorrect AHS output from amazon-braket-default-simulator 1.17.0 

### ISSUE THREAD

**Issue by balewski** [aws/amazon-braket-examples#301]
**Describe the bug**
the Podman container build with 
` pip3 install  quera_ahs_utils  `
assembles non-functioning  AHS Braket library.

**To Reproduce**
When I run AHS emulation of a simple few atom system I see only 'ggggg..' state is being produced.
Also I see this warning:
`/usr/local/lib/python3.10/dist-packages/braket/analog_hamiltonian_simulator/rydberg/rydberg_simulator_helpers.py:504: UserWarning: The solver uses intermediate time value that is larger than the maximum time value specified. The final time value of the specified range is used as an approximation.
`
Despite I used a lot of steps for a Hamiltonina which lasts for just 1.2 us
```
job = device.run(ahs_program, shots=shots, steps=480, solver_method="bdf")
```
 **Known workaround (if applicable)**
I think it is related to the newer amazon-braket version. I have an old image build about 2 months ago which uses this this software stack and it  has no problems - all my emulations work
```
$ pip3 list |grep braket
amazon-braket-default-simulator 1.14.0.post0
amazon-braket-schemas           1.17.0
amazon-braket-sdk               1.42.1
```
But when I build a fresh image, I get this software  stack, for which AHS is producing only 'ggggg...' state.
```
amazon-braket-default-simulator 1.17.0
amazon-braket-schemas           1.18.0
amazon-braket-sdk               1.48.1
```

**Comment by shpface** [comment]
Thanks for this bug report. We have addressed the root issue in [aws/amazon-braket-default-simulator#187](https://github.com/aws/amazon-braket-default-simulator-python/pull/187). This is released in amazon-braket-default-simulator 1.18.2. Feel free to give that updated version a try and let us know if the issue persists.

**Comment by balewski** [comment]
I confirm this software stack works again - thank you
Jan
amazon-braket-default-simulator 1.18.2
amazon-braket-schemas           1.18.0
amazon-braket-sdk               1.49.0

**Comment by balewski** [comment]
thanks for the help

**Comment by christianbmadsen** [comment]
@balewski Thank you so much for all the recent feedback, triaging and validation of issues. I would love to jump on a call with you to chat about your general experience using Braket. If you have time and are willing could you send a quick note to amazon-braket-github-issues@amazon.com? That should allow me to coordinate a meeting.
