### ISSUE TITLE
Solve an annealing problem with `Device.run`

### ISSUE THREAD

**Issue by teaguetomesh** [aws/amazon-braket-examples#66]
In the [D-Wave MaxCut example](https://github.com/aws/amazon-braket-examples/blob/main/examples/quantum_annealing/Dwave_MaximumCut.ipynb), an `AwsDevice` is created in the 4th code block:

``` python
device = AwsDevice("arn:aws:braket:::device/qpu/d-wave/Advantage_system1")
```

However, `device` is never used again in the notebook. Instead, the MaxCut problem is solved using a sampler object:

``` python
sampler = BraketDWaveSampler(s3_folder,'arn:aws:braket:::device/qpu/d-wave/Advantage_system1')
sampler = EmbeddingComposite(sampler)
response = sampler.sample_qubo(Q, chain_strength=chainstrength, num_reads=numruns)
```

Is this the only way to use the D-Wave devices and solve annealing problems? Or is it possible to use the `device.run()` function? The `run` function has the option of passing in a `Problem` as the task specification (instead of a `Circuit`), but I have so far been unable to get this to work.

Any help or directions to relevant tutorials would be greatly appreciated!

**Comment by wrasmuss** [comment]
@teaguetomesh Thanks for pointing out the unneeded creation of the AwsDevice instance.

As far solving a problem with AwsDevice.run it is definitely possible but it is less streamlined and we generally encourage the Ocean plugin route. Perhaps if you can shed some light on your use case we can make some recommendations.

**Comment by ajberdy** [comment]
Hi @teaguetomesh, here is a minimal example for finding a solution to a QUBO problem using `AwsDevice.run`:

```
s3_folder = ("amazon-braket-Your-Bucket-Name", "folder-name")

device = AwsDevice("arn:aws:braket:::device/qpu/d-wave/DW_2000Q_6")
problem = Problem(
    problem_type=ProblemType.QUBO,
    linear={30: 0.0},
    quadratic={},
)

task = device.run(problem, s3_folder)
print(task.result())
```

**Comment by teaguetomesh** [comment]
Thanks for the example. The above code runs fine for me, but trying a problem with quadratic terms seems to be breaking:

``` python
problem = Problem(
    problem_type=ProblemType.QUBO,
    linear={0: 1.1, 1: 0.8},
    quadratic={(0, 1): -2.0},
)
```

Running this problem gives an error: 
``` python
ValidationException: An error occurred (ValidationException) when calling the CreateQuantumTask operation: Unknown couplers specified: {(0, 1)}
```

But [this](https://github.com/aws/amazon-braket-sdk-python/blob/182df73d2d07d4bc9ee4666f4f88dd7e25cf4c98/src/braket/annealing/problem.py#L41) is how the quadratic terms should be represented, no?

**Comment by ajberdy** [comment]
Hi @teaguetomesh, you are using the correct format. The issue is that (0, 1) is not a valid coupler for the device you are using. You can see all valid couplers for a D-Wave device with `device.properties.provider.couplers`. The two chips have different topologies (`device.properties.provider.topology`) and hence different sets of qubits and couplers. Take a look at [D-Wave's documentation of their device's topology](https://docs.dwavesys.com/docs/latest/c_gs_4.html) if you'd like to learn more!

Your example works if you select 2 qubits from a valid coupler:
```
device = AwsDevice("arn:aws:braket:::device/qpu/d-wave/DW_2000Q_6")

problem = Problem(
    problem_type=ProblemType.QUBO,
    linear={0: 1.1, 4: 0.8},
    quadratic={(0, 4): -2.0},
)
task = device.run(problem, s3_folder)
print(task.result())
```

**Comment by teaguetomesh** [comment]
I see, thank you this is super helpful!

Are there functions available within Braket that could do this mapping for me? Specifically, taking a generic `Problem` on variables `[0, 1, 2,...n]` and map them to valid couplers on the D-Wave devices?

**Comment by ajberdy** [comment]
The sampler featured in the [braket ocean plugin](https://github.com/aws/amazon-braket-ocean-plugin-python/) is designed to abstract these sorts of things and will generally be more convenient to work with on a higher level. The example notebooks provide examples for its use. Meanwhile, `AwsDevice` is a lower-level construct for directly running circuits and problems on a device through Braket, without the additional preprocessing.

**Comment by teaguetomesh** [comment]
I see - in that case I suppose it makes more sense to utilize the samplers from the Ocean plugin for our use case. Thanks for the help!
