### ISSUE TITLE
Exceptions when pip install and import tensorflow-quantum

### ISSUE THREAD

**Issue by Darkhunter9** [aws/amazon-braket-examples#93]
Our project needs to define a quantum convolutional layer. When implementing it, we choose to use tensorflow and tensorflow-quantum library. tensorflow-quantum is not installed by default under conda_braket environment. When pip install it, it seems there's a version conflict with cirq and an exception is thrown. However it is not easy to upgrade/downgrade cirq or tensorflow as they have dependencies with multiple other quantum libraries.

The problem can be reproduced on amazon braket notebooks
```python
import tensorflow
import cirq
print(tensorflow.__version__) # 2.6.0
print(cirq.__version__) # 0.9.1

!pip install tensorflow-quantum

import tensorflow_quantum
```

The exception is shown as attached:
![tfq_error_reproduce](https://user-images.githubusercontent.com/40048121/142705407-0ee1d805-e954-4fc9-8634-d363501a0661.png)

**Comment by licedric** [comment]
Hi Darkhunter9,

Thank you for raising this issue. The Amazon Braket notebook instances do not officially support TensorFlow Quantum; however the problem you described seems to be a version conflict in TFQ itself, see e.g. https://github.com/tensorflow/quantum/issues/630. 

The following works for me:
```
!pip install tensorflow==2.4.1
!pip install tensorflow-quantum==0.5.1
# Cirq linking seems to be broken, so reinstall the core package
!pip install --no-deps --force-reinstall cirq-core==0.11.0

import tensorflow_quantum # works fine
```

**Comment by Darkhunter9** [comment]
> Hi Darkhunter9,
> 
> Thank you for raising this issue. The Amazon Braket notebook instances do not officially support TensorFlow Quantum; however the problem you described seems to be a version conflict in TFQ itself, see e.g. [tensorflow/quantum#630](https://github.com/tensorflow/quantum/issues/630).
> 
> The following works for me:
> 
> ```
> !pip install tensorflow==2.4.1
> !pip install tensorflow-quantum==0.5.1
> # Cirq linking seems to be broken, so reinstall the core package
> !pip install --no-deps --force-reinstall cirq-core==0.11.0
> 
> import tensorflow_quantum # works fine
> ```

Hi Cedric:
    Thanks for the solution! This looks like the right choice, although I still worry a little bit about the dependency between cirq and other libraries that communicate directly with the quantum devices. I'll test and keep you posted.
